apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: home-media
spec:
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
    nodePort: 30096
  selector:
    app: jellyfin
  type: NodePort
status:
  loadBalancer: {}
